require 'nokogiri'
require 'pcaprub'

module Wiresnark module DSL end end

require_relative 'wiresnark/configuration'
require_relative 'wiresnark/dsl/common_dsl'
require_relative 'wiresnark/dsl/packet_dsl'
require_relative 'wiresnark/dsl/generator_dsl'
require_relative 'wiresnark/dsl/monitor_dsl'
require_relative 'wiresnark/dsl/wiresnark_dsl'
require_relative 'wiresnark/executable'
require_relative 'wiresnark/generator'
require_relative 'wiresnark/interface'
require_relative 'wiresnark/net_fpga'
require_relative 'wiresnark/net_fpga/port'
require_relative 'wiresnark/packet'
require_relative 'wiresnark/reg_parser'
require_relative 'wiresnark/runner'
require_relative 'wiresnark/stream'
require_relative 'wiresnark/xml_parser'
